#
# Makefile for the Linux Wireless network device drivers.
#

ifeq ($(WISKY_ENABLE_WIFI),y)
obj-$(WISKY_WIFI_RTL8192C)	+= rkusbwifi/
obj-$(WISKY_WIFI_RTL8188EU)	+= rkusbwifi/
obj-$(WISKY_WIFI_RK903)	+= rkwifi/
obj-$(WISKY_WIFI_RK901)	+= rkwifi/
obj-$(WISKY_WIFI_BCM4330)	+= rkwifi/
endif