/*
 *  wisky/config/wisky_config_main.c
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 **************************************************
 * log:
 * 1. 2020421 by cd huang
 * 	> Driver for mid function module config
 *
 */
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/moduleparam.h>
#include <linux/init.h>
#include <linux/delay.h>
#include <linux/device.h>
#include <linux/errno.h>
#include <linux/types.h>
#include <linux/err.h>
#include <linux/stat.h>	 /* permission constants */
#include <asm/sizes.h>

#define CONFIG_CLASS_NAME	"wisky"
#define CONFIG_BUF_SIZE		SZ_4K


char config_buf[CONFIG_BUF_SIZE];

static struct class *config_class = NULL;

const char config_info[][MAX_CONFIG_BUFFLEN] = {
	ANDROID_CONFIG_J1, ANDROID_CONFIG_ZA, 
	ANDROID_CONFIG_A1, ANDROID_CONFIG_A2, ANDROID_CONFIG_A3, ANDROID_CONFIG_A4,
	ANDROID_CONFIG_C1, ANDROID_CONFIG_C2, ANDROID_CONFIG_C3, ANDROID_CONFIG_C4,
	ANDROID_CONFIG_C5, ANDROID_CONFIG_C6, ANDROID_CONFIG_C7, ANDROID_CONFIG_C8,
	ANDROID_CONFIG_C9, ANDROID_CONFIG_CA, ANDROID_CONFIG_CB, ANDROID_CONFIG_CC,
	ANDROID_CONFIG_D1, ANDROID_CONFIG_D2, ANDROID_CONFIG_D3, ANDROID_CONFIG_D4,
	ANDROID_CONFIG_E1, ANDROID_CONFIG_E2, ANDROID_CONFIG_E5, ANDROID_CONFIG_E7,
	ANDROID_CONFIG_F1, ANDROID_CONFIG_F6, ANDROID_CONFIG_F7, ANDROID_CONFIG_F8,
	ANDROID_CONFIG_G1, ANDROID_CONFIG_G2, ANDROID_CONFIG_I1, ANDROID_CONFIG_J2,
	ANDROID_CONFIG_L1,
	ANDROID_CONFIG_L2, ANDROID_CONFIG_M1, ANDROID_CONFIG_M5, ANDROID_CONFIG_M6,
	ANDROID_CONFIG_Z1, ANDROID_CONFIG_Z2, ANDROID_CONFIG_Z3, ANDROID_CONFIG_Z4,
	ANDROID_CONFIG_Z5, ANDROID_CONFIG_Z6, ANDROID_CONFIG_Z7, ANDROID_CONFIG_Z8,
	ANDROID_CONFIG_Z9, ANDROID_CONFIG_ZB, ANDROID_CONFIG_ZC,
	ANDROID_CONFIG_ZD, ANDROID_CONFIG_ZE, ANDROID_CONFIG_ZF, ANDROID_CONFIG_ZG,
	ANDROID_CONFIG_ZH, ANDROID_CONFIG_ZI, ANDROID_CONFIG_ZJ, ANDROID_CONFIG_ZK,
	ANDROID_CONFIG_ZL, ANDROID_CONFIG_ZM, ANDROID_CONFIG_ZN, ANDROID_CONFIG_ZO,
	ANDROID_CONFIG_ZP, ANDROID_CONFIG_ZQ, ANDROID_CONFIG_ZR, ANDROID_CONFIG_ZS,
	ANDROID_CONFIG_ZT, ANDROID_CONFIG_ZU, ANDROID_CONFIG_ZV, ANDROID_CONFIG_ZW,
	ANDROID_CONFIG_ZX, ANDROID_CONFIG_ZY, ANDROID_CONFIG_ZZ, ANDROID_CONFIG_Y1,
	ANDROID_CONFIG_Y2, ANDROID_CONFIG_Y3, ANDROID_CONFIG_Y4, ANDROID_CONFIG_Y5,
	ANDROID_CONFIG_Y6, ANDROID_CONFIG_Y7, ANDROID_CONFIG_Y8, ANDROID_CONFIG_Y9,
	ANDROID_CONFIG_YA, ANDROID_CONFIG_YB, ANDROID_CONFIG_YC, ANDROID_CONFIG_YD,
	ANDROID_CONFIG_YE, ANDROID_CONFIG_YF, ANDROID_CONFIG_YG, ANDROID_CONFIG_YH,
	ANDROID_CONFIG_YI, ANDROID_CONFIG_YJ, ANDROID_CONFIG_YK, ANDROID_CONFIG_YL,
	ANDROID_CONFIG_YM, ANDROID_CONFIG_YN, ANDROID_CONFIG_YO, ANDROID_CONFIG_YP, 
	ANDROID_CONFIG_YQ, ANDROID_CONFIG_YR, ANDROID_CONFIG_YS, ANDROID_CONFIG_YT, 
	ANDROID_CONFIG_YU, ANDROID_CONFIG_YV, ANDROID_CONFIG_YW, ANDROID_CONFIG_YX,
	ANDROID_CONFIG_YY, ANDROID_CONFIG_YZ, ANDROID_CONFIG_X1, ANDROID_CONFIG_X2,
	ANDROID_CONFIG_X3, ANDROID_CONFIG_X4, ANDROID_CONFIG_X5, ANDROID_CONFIG_X6,
	ANDROID_CONFIG_X7, ANDROID_CONFIG_X8, ANDROID_CONFIG_X9, ANDROID_CONFIG_XA,
	ANDROID_CONFIG_XB, ANDROID_CONFIG_XC, ANDROID_CONFIG_XD, ANDROID_CONFIG_XE,
	ANDROID_CONFIG_XF, ANDROID_CONFIG_XG, ANDROID_CONFIG_XH, ANDROID_CONFIG_XI,
	ANDROID_CONFIG_XJ, ANDROID_CONFIG_XK, ANDROID_CONFIG_XL, ANDROID_CONFIG_XM,
	ANDROID_CONFIG_XN, ANDROID_CONFIG_XO, ANDROID_CONFIG_XP, ANDROID_CONFIG_XQ,
	ANDROID_CONFIG_XR, ANDROID_CONFIG_XS, ANDROID_CONFIG_XT, ANDROID_CONFIG_XU,
	ANDROID_CONFIG_XV, ANDROID_CONFIG_XW, ANDROID_CONFIG_XX, ANDROID_CONFIG_XY,
	ANDROID_CONFIG_XZ,ANDROID_CONFIG_W1,ANDROID_CONFIG_W2,ANDROID_CONFIG_W3,
	ANDROID_CONFIG_W4,
	"\0",
};

const char config_info_str[][MAX_CONFIG_BUFFLEN] = {
	"ANDROID_CONFIG_J1", "ANDROID_CONFIG_ZA",
	"ANDROID_CONFIG_A1", "ANDROID_CONFIG_A2", "ANDROID_CONFIG_A3", "ANDROID_CONFIG_A4",
	"ANDROID_CONFIG_C1", "ANDROID_CONFIG_C2", "ANDROID_CONFIG_C3", "ANDROID_CONFIG_C4",
	"ANDROID_CONFIG_C5", "ANDROID_CONFIG_C6", "ANDROID_CONFIG_C7", "ANDROID_CONFIG_C8",
	"ANDROID_CONFIG_C9", "ANDROID_CONFIG_CA", "ANDROID_CONFIG_CB", "ANDROID_CONFIG_CC",
	"ANDROID_CONFIG_D1", "ANDROID_CONFIG_D2", "ANDROID_CONFIG_D3", "ANDROID_CONFIG_D4",
	"ANDROID_CONFIG_E1", "ANDROID_CONFIG_E2", "ANDROID_CONFIG_E5", "ANDROID_CONFIG_E7",
	"ANDROID_CONFIG_F1", "ANDROID_CONFIG_F6", "ANDROID_CONFIG_F7", "ANDROID_CONFIG_F8",
	"ANDROID_CONFIG_G1", "ANDROID_CONFIG_G2", "ANDROID_CONFIG_I1", "ANDROID_CONFIG_J2",
	"ANDROID_CONFIG_L1",
	"ANDROID_CONFIG_L2", "ANDROID_CONFIG_M1", "ANDROID_CONFIG_M5", "ANDROID_CONFIG_M6",
	"ANDROID_CONFIG_Z1", "ANDROID_CONFIG_Z2", "ANDROID_CONFIG_Z3", "ANDROID_CONFIG_Z4",
	"ANDROID_CONFIG_Z5", "ANDROID_CONFIG_Z6", "ANDROID_CONFIG_Z7", "ANDROID_CONFIG_Z8",
	"ANDROID_CONFIG_Z9", "ANDROID_CONFIG_ZB", "ANDROID_CONFIG_ZC",
	"ANDROID_CONFIG_ZD", "ANDROID_CONFIG_ZE", "ANDROID_CONFIG_ZF", "ANDROID_CONFIG_ZG",
	"ANDROID_CONFIG_ZH", "ANDROID_CONFIG_ZI", "ANDROID_CONFIG_ZJ", "ANDROID_CONFIG_ZK",
	"ANDROID_CONFIG_ZL", "ANDROID_CONFIG_ZM", "ANDROID_CONFIG_ZN", "ANDROID_CONFIG_ZO",
	"ANDROID_CONFIG_ZP", "ANDROID_CONFIG_ZQ", "ANDROID_CONFIG_ZR", "ANDROID_CONFIG_ZS",
	"ANDROID_CONFIG_ZT", "ANDROID_CONFIG_ZU", "ANDROID_CONFIG_ZV", "ANDROID_CONFIG_ZW",
	"ANDROID_CONFIG_ZX", "ANDROID_CONFIG_ZY", "ANDROID_CONFIG_ZZ", "ANDROID_CONFIG_Y1",
	"ANDROID_CONFIG_Y2", "ANDROID_CONFIG_Y3", "ANDROID_CONFIG_Y4", "ANDROID_CONFIG_Y5",
	"ANDROID_CONFIG_Y6", "ANDROID_CONFIG_Y7", "ANDROID_CONFIG_Y8", "ANDROID_CONFIG_Y9",
	"ANDROID_CONFIG_YA", "ANDROID_CONFIG_YB", "ANDROID_CONFIG_YC", "ANDROID_CONFIG_YD",
	"ANDROID_CONFIG_YE", "ANDROID_CONFIG_YF", "ANDROID_CONFIG_YG", "ANDROID_CONFIG_YH",
	"ANDROID_CONFIG_YI", "ANDROID_CONFIG_YJ", "ANDROID_CONFIG_YK", "ANDROID_CONFIG_YL",
	"ANDROID_CONFIG_YM", "ANDROID_CONFIG_YN", "ANDROID_CONFIG_YO", "ANDROID_CONFIG_YP",
	"ANDROID_CONFIG_YQ", "ANDROID_CONFIG_YR", "ANDROID_CONFIG_YS", "ANDROID_CONFIG_YT", 
	"ANDROID_CONFIG_YU", "ANDROID_CONFIG_YV", "ANDROID_CONFIG_YW", "ANDROID_CONFIG_YX",
	"ANDROID_CONFIG_YY", "ANDROID_CONFIG_YZ", "ANDROID_CONFIG_X1", "ANDROID_CONFIG_X2",
	"ANDROID_CONFIG_X3", "ANDROID_CONFIG_X4", "ANDROID_CONFIG_X5", "ANDROID_CONFIG_X6",
	"ANDROID_CONFIG_X7", "ANDROID_CONFIG_X8", "ANDROID_CONFIG_X9", "ANDROID_CONFIG_XA",
	"ANDROID_CONFIG_XB", "ANDROID_CONFIG_XC", "ANDROID_CONFIG_XD", "ANDROID_CONFIG_XE",
	"ANDROID_CONFIG_XF", "ANDROID_CONFIG_XG", "ANDROID_CONFIG_XH", "ANDROID_CONFIG_XI",
	"ANDROID_CONFIG_XJ", "ANDROID_CONFIG_XK", "ANDROID_CONFIG_XL",  "ANDROID_CONFIG_XM",
	"ANDROID_CONFIG_XN", "ANDROID_CONFIG_XO", "ANDROID_CONFIG_XP", "ANDROID_CONFIG_XQ",
	"ANDROID_CONFIG_XR", "ANDROID_CONFIG_XS", "ANDROID_CONFIG_XT", "ANDROID_CONFIG_XU",
	"ANDROID_CONFIG_XV", "ANDROID_CONFIG_XW", "ANDROID_CONFIG_XX", "ANDROID_CONFIG_XY",
	"ANDROID_CONFIG_XZ", "ANDROID_CONFIG_W1", "ANDROID_CONFIG_W2", "ANDROID_CONFIG_W3",
	"ANDROID_CONFIG_W4",
	"\0",
};

static void config_write_info(void)
{
	int index=0;
	char func_buf[MAX_CONFIG_BUFFLEN] = {0};

	while(config_info[index][0] != 0){
	//write string to file	
		strcat(config_buf, config_info_str[index]);
		sprintf(func_buf, "=%s\n", config_info[index]);
		strcat(config_buf, func_buf);
		index++;
	}
	strcat(config_buf, "\0");
}

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(2, 6, 37))
static ssize_t wisky_config_show(struct class *cls, struct class_attribute *attr, char *buf)
#else
static ssize_t wisky_config_show(struct class *cls, char *buf)
#endif
{
	memcpy(buf, config_buf, sizeof(config_buf));
	return strlen(config_buf);
}

static CLASS_ATTR(wisky_conf, 0444, wisky_config_show, NULL);

static int __init wisky_config_init(void)
{
	int ret = 0;

	config_class = class_create(THIS_MODULE, CONFIG_CLASS_NAME);
	if(IS_ERR(config_class)){
		pr_err("%s: create gps class failed!\n", __FUNCTION__);
	}

	ret = class_create_file(config_class, &class_attr_wisky_conf);
	if(ret){
		pr_err("%s: calss attr power create failed\n", __FUNCTION__);
	}

	memset(config_buf, 0, sizeof(config_buf));

	config_write_info();

	pr_info("wisky mid function config length %d\n", strlen(config_buf));
	
	return ret;
}

static void __exit wisky_config_exit(void)
{
	class_remove_file(config_class, &class_attr_wisky_conf);
	class_destroy(config_class);
}

module_init(wisky_config_init);
module_exit(wisky_config_exit);


MODULE_AUTHOR("cd huang");
MODULE_DESCRIPTION("wisky function config driver");
MODULE_LICENSE("GPL");


