#rkwifi packed Makefile
# (gwl)

obj-$(WISKY_WIFI_RK903) += rk_wifi_config.o
obj-$(WISKY_WIFI_RK901) += rk_wifi_config.o
obj-$(WISKY_WIFI_BCM4330) += rk_wifi_config.o

.PHONY: clean

clean:
	find . -name '*.o*' -exec rm -f {} \; 
